assist = "files/assist.txt"
animals = "files/animals.txt"
reviews = "files/reviews.txt"
employees = "files/employees.json"
animals_cured = "files/animals_cured.json"
log = "files/log.json"
most_using_command = "files/most_using_command.json"